version: 2

jobs:
  "golang-1.20":
    docker:
      - image: cimg/go:1.20
    steps:
      - checkout
      - run: 'sudo apt-get update'
      - run: 'sudo apt-get install -y zlib1g-dev'
      - run: 'wget https://github.com/DataDog/zstd/files/2246767/mr.zip'
      - run: 'unzip mr.zip'
      - run: 'go build'
      - run: 'PAYLOAD=`pwd`/mr go test -v'
      - run: 'PAYLOAD=`pwd`/mr go test -bench .'
  "golang-latest":
    docker:
      - image: cimg/go:1.21
    steps:
      - checkout
      - run: 'sudo apt-get update'
      - run: 'sudo apt-get install -y zlib1g-dev'
      - run: 'wget https://github.com/DataDog/zstd/files/2246767/mr.zip'
      - run: 'unzip mr.zip'
      - run: 'go build'
      - run: 'PAYLOAD=`pwd`/mr go test -v'
      - run: 'PAYLOAD=`pwd`/mr go test -bench .'

workflows:
  version: 2
  build:
    jobs:
      - "golang-1.20"
      - "golang-latest"
